### PR TITLE
Various new tsv functionalities

### PR DESCRIPTION
**Pull request by sven-nm**
- Improves gitignore; 
- completes README; 
- adds a tsv_sample.tsv in data;
- adds tsv manipulation functions to helpers/tsv; 
- adds torch to setup.py packages; 
- adds some tests for tsv manipulation functions

### CODE REVIEW

**Comment by mromanello** [comment]
Thanks a lot, @sven-nm! Would it be possible to add a test for `tsv_to_torch_datasets`? 
And also bump the version to `0.3.0`.

**Comment by sven-nm** [comment]
@mromanello, I think its all good now, I let you have a final check before merging.

**Comment by sven-nm** [comment]
feature missing : #3 does not allow for cutting and recycling samples with a length superior to the model's `max_length`. To be fixed before merge.

Also : untokenize the dataset. tokenization should be done afterwards.

**Comment by sven-nm** [comment]
@mromanello @simon-clematide added just a few functionalities there and corrected [the previous comment](https://github.com/hipe-eval/HIPE-pycommons/pull/3#issuecomment-1087585355), now ready for a merge ;-)

**Pull request merged**
